export enum ErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  SERVER_ERROR = "SERVER_ERROR",
}

export enum ErrorStatusCode {
  VALIDATION_ERROR = 422,
  AUTHENTICATION_ERROR = 401,
  NOT_FOUND = 404,
  BAD_REQUEST = 400,
  SERVER_ERROR = 500,
}
