export enum ErrorCode {
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  BAD_REQUEST = "BAD_REQUEST",
  NOT_FOUND = "NOT_FOUND",
  SERVER_ERROR = "SERVER_ERROR",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
}

export enum ErrorStatusCode {
  AUTHENTICATION_ERROR = 401,
  BAD_REQUEST = 400,
  NOT_FOUND = 404,
  SERVER_ERROR = 500,
  VALIDATION_ERROR = 422,
  SERVICE_UNAVAILABLE = 503,
}
